import { ChangePasswordState } from 'app/components/AccountSettings/components/ChangePassword/slice/types';
import { CommunityState } from 'app/components/Community/slice/types';
import { InputState } from 'app/components/InputSearch/slice/types';
import { GlobalLoadingState } from 'app/components/Loading/slice/types';
import { UserInfoState } from 'app/components/MyProfileBio/slice/types';
import { AccountingReleasesState } from 'app/pages/Accounting/components/ReleasesTab/slice/types';
import { AccountingTrackState } from 'app/pages/Accounting/components/TracksTab/slice/types';
import { AccountingState } from 'app/pages/Accounting/slice/types';
import { BannerState } from 'app/pages/Banner/slice/types';
import { CashOutsState } from 'app/pages/CashOut/slice/types';
import { ForgotPasswordState } from 'app/pages/ForgotPassword/slice/types';
import { GeneralState } from 'app/pages/General/types';
import { GenresState } from 'app/pages/Genres/slice/types';
import { LabelsState } from 'app/pages/LabelsPage/slice/types';
import { AuthState } from 'app/pages/Login/slice/types';
import { CreatesState } from 'app/pages/PageCrate/slice/types';
import { ReleaseDetailState } from 'app/pages/ReleaseDetail/slice/types';
import { ReleasesState } from 'app/pages/Releases/slice/types';
import { SamplesState } from 'app/pages/Samples/slice/types';
import { SectionsState } from 'app/pages/Sections/slice/types';
import { ServicesState } from 'app/pages/Services/slice/types';
import { SignupState } from 'app/pages/Signup/slice/types';
import { SubscriptionsState } from 'app/pages/Subscriptions/slice/types';
import { TagsState } from 'app/pages/Tags/slice/types';
import { TrackKeysState } from 'app/pages/TrackKeys/slice/types';
import { PlayerAudioState } from 'app/pages/Tracks/playerAudio/types';
import { TrackState } from 'app/pages/Tracks/slice/types';
import { TrackDetailState } from 'app/pages/TracksDetail/slice/types';
import { WishlistState } from 'app/pages/Wishlist/slice/types';

export interface RootState {
  auth?: AuthState;
  track?: TrackState;
  signup?: SignupState;
  genres?: GenresState;
  general?: GeneralState;
  globalLoading?: GlobalLoadingState;
  player?: PlayerAudioState;
  sections?: SectionsState;
  trackDetail?: TrackDetailState;
  trackKeys?: TrackKeysState;
  tags?: TagsState;
  releases?: ReleasesState;
  forgotPassword?: ForgotPasswordState;
  crates: CreatesState;
  community?: CommunityState;
  banner?: BannerState;
  services?: ServicesState;
  labels?: LabelsState;
  userDetails?: UserInfoState;
  releaseDetail?: ReleaseDetailState;
  wishlists?: WishlistState;
  samples?: SamplesState;
  cashout?: CashOutsState;
  changepassword?: ChangePasswordState;
  accounting?: AccountingState;
  accountingTrack?: AccountingTrackState;
  accountingReleases?: AccountingReleasesState;
  input?: InputState;
  subscription?: SubscriptionsState;
}
